import { createHash } from 'node:crypto';
import { beforeAll, describe, expect, it } from 'vitest';

let integrity;
beforeAll(async () => {
  const moduleUrl = new URL('../lib/integrity.mjs', import.meta.url);
  integrity = await import(/* @vite-ignore */ moduleUrl.href);
});

const css = Buffer.from(':root { --stara-example: #123456; }\n', 'utf8');
const revision = '1234567890abcdef1234567890abcdef12345678';
const consumer = () => ({ revision });
const provenance = () => ({
  sourceRevision: revision,
  cssSha256: createHash('sha256').update(css).digest('hex'),
});

describe('hashBytes: SHA-256 of exact generated bytes', () => {
  it.each([
    ['', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
    ['abc', 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'],
  ])('matches the fixed SHA-256 vector for %j', (input, expected) => {
    expect(integrity.hashBytes(Buffer.from(input))).toBe(expected);
  });

  it('hashes binary bytes without text conversion', () => {
    const bytes = Buffer.from([0, 255, 254, 128, 13, 10, 0]);
    expect(integrity.hashBytes(bytes)).toBe(createHash('sha256').update(bytes).digest('hex'));
  });

  it('does not normalize CRLF or final newlines', () => {
    const hashes = ['a\n', 'a\r\n', 'a'].map((value) => integrity.hashBytes(Buffer.from(value)));
    expect(new Set(hashes).size).toBe(3);
  });
});

describe('verifyTokenArtifact: artifact and immutable revision must both match', () => {
  it('accepts matching bytes, provenance, and pinned consumer revision', () => {
    expect(() => integrity.verifyTokenArtifact(css, provenance(), consumer())).not.toThrow();
  });

  it('rejects a one-byte modification with otherwise matching provenance', () => {
    const changed = Buffer.from(css);
    changed[10] ^= 1;
    expect(() => integrity.verifyTokenArtifact(changed, provenance(), consumer())).toThrow();
  });

  it('rejects line-ending conversion after generation', () => {
    const changed = Buffer.from(css.toString().replaceAll('\n', '\r\n'));
    expect(() => integrity.verifyTokenArtifact(changed, provenance(), consumer())).toThrow();
  });

  it('rejects an empty artifact carrying a nonempty artifact hash', () => {
    expect(() =>
      integrity.verifyTokenArtifact(Buffer.alloc(0), provenance(), consumer()),
    ).toThrow();
  });

  it('rejects correctly hashed CSS from a different source revision', () => {
    expect(() =>
      integrity.verifyTokenArtifact(
        css,
        { ...provenance(), sourceRevision: 'f'.repeat(40) },
        consumer(),
      ),
    ).toThrow();
  });

  it('rejects a consumer changed independently of matching CSS/provenance', () => {
    expect(() =>
      integrity.verifyTokenArtifact(css, provenance(), { revision: 'a'.repeat(40) }),
    ).toThrow();
  });

  it.each([undefined, null, '', 'main', 'a'.repeat(39), 'a'.repeat(41), 'g'.repeat(40), 123])(
    'rejects malformed source or consumer revision %j, even when equal',
    (invalid) => {
      expect(() =>
        integrity.verifyTokenArtifact(
          css,
          { ...provenance(), sourceRevision: invalid },
          { revision: invalid },
        ),
      ).toThrow();
    },
  );

  it.each([
    undefined,
    null,
    '',
    '0'.repeat(64),
    'a'.repeat(63),
    'a'.repeat(65),
    'z'.repeat(64),
    123,
  ])('rejects missing/malformed/mismatched cssSha256 %j', (cssSha256) => {
    expect(() =>
      integrity.verifyTokenArtifact(css, { ...provenance(), cssSha256 }, consumer()),
    ).toThrow();
  });

  it.each([undefined, null, {}])('rejects absent provenance %j', (value) => {
    expect(() => integrity.verifyTokenArtifact(css, value, consumer())).toThrow();
  });

  it.each([undefined, null, {}])('rejects absent consumer record %j', (value) => {
    expect(() => integrity.verifyTokenArtifact(css, provenance(), value)).toThrow();
  });
});
